apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2023.10.x # auto-update to semver bugfixes only 
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authentik
  values: # paste contents of upstream values.yaml below, indented 4 spaces 
    authentik:
      # -- Log level for server and worker
      log_level: info
      # -- Secret key used for cookie singing and unique user IDs,
      # don't change this after the first install
      secret_key: "ilovesingingcookies"
      postgresql:
        password: "Iamaverysecretpassword"
    env:
      AUTHENTIK_BOOTSTRAP_PASSWORD: "iamusedbyhumanz"
      AUTHENTIK_BOOTSTRAP_TOKEN: "iamusedbymachinez"
    redis:
      master:
        persistence:
          size: 1Gi
    postgresql:
      postgresqlPassword: "Iamaverysecretpassword"
      persistence:
        size: 1Gi 
    ingress:
      enabled: true
      ingressClassName: "traefik" 
      annotations: {}
      labels: {}
      hosts:
        - host: authentik.ffd.link
          paths:
            - path: "/"
              pathType: Prefix
      tls: []
